%{
Code to demonstrate a pair of square Helmholtz coils generating a magnetic field.
The HH coil configuration does not produce zero field strength at the
centre, but rather a volume of uniform field strength and direction (Grad(B) is small, approaching zero).
Anti-Helmholtz pair can be generated by reversing the current in one of the
coils.
Each coil is formed of four straight wires, each wire represented by 100
points. Field is evaluated at 19 points on each axis inside the volume of
interest.
Script is based on ideas found at various free sources found online, but
the construction was my own work.
%}
clc
close all
clear all

Nx=19;
Nz=19;  
Ny=19;  
N=100;   % length of the wire 

I1=1;    % coil 1 current 
I2=1;    % coil 2 current 
u0=1;   % permeability

%--------------------------------------------------------------------------

%Wire at Y=-5, Z=-5, parallel to x-axis                     : Coil 1
Xw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=-5.*ones(N+1,1); % Y-coordinates of the wire
Zw11=-5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(I1*u0./(4*pi*(R.^3))).*Xcross;
            By1=(I1*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(I1*u0./(4*pi*(R.^3))).*Zcross;
    
            BX1(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY1(a,b,c)=0;
            BZ1(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX1(a,b,c)=BX1(a,b,c)+Bx1(i);
                BY1(a,b,c)=BY1(a,b,c)+By1(i);
                BZ1(a,b,c)=BZ1(a,b,c)+Bz1(i);
            end
        end
    end
end

%Wire at Y=-5, Z=+5, parallel to x-axis                      : Coil 1
Xw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=-5.*ones(N+1,1); % Y-coordinates of the wire
Zw11=5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(-I1*u0./(4*pi*(R.^3))).*Xcross;
            By1=(-I1*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(-I1*u0./(4*pi*(R.^3))).*Zcross;
    
            BX2(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY2(a,b,c)=0;
            BZ2(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX2(a,b,c)=BX2(a,b,c)+Bx1(i);
                BY2(a,b,c)=BY2(a,b,c)+By1(i);
                BZ2(a,b,c)=BZ2(a,b,c)+Bz1(i);
            end
        end
    end
end

%Wire at Y=-5, X=+5, parallel to z-axis                       : Coil 1
Zw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=-5.*ones(N+1,1); % Y-coordinates of the wire
Xw11=5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(I1*u0./(4*pi*(R.^3))).*Xcross;
            By1=(I1*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(I1*u0./(4*pi*(R.^3))).*Zcross;
    
            BX7(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY7(a,b,c)=0;
            BZ7(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX7(a,b,c)=BX7(a,b,c)+Bx1(i);
                BY7(a,b,c)=BY7(a,b,c)+By1(i);
                BZ7(a,b,c)=BZ7(a,b,c)+Bz1(i);
            end
        end
    end
end

%Wire at Y=-5, X=-5, parallel to z-axis                       : Coil 1
Zw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=-5.*ones(N+1,1); % Y-coordinates of the wire
Xw11=-5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(-I1*u0./(4*pi*(R.^3))).*Xcross;
            By1=(-I1*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(-I1*u0./(4*pi*(R.^3))).*Zcross;
    
            BX8(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY8(a,b,c)=0;
            BZ8(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX8(a,b,c)=BX8(a,b,c)+Bx1(i);
                BY8(a,b,c)=BY8(a,b,c)+By1(i);
                BZ8(a,b,c)=BZ8(a,b,c)+Bz1(i);
            end
        end
    end
end

%--------------------------------------------------------------------------

%Wire at Y=+5, Z=-5, parallel to x-axis                      : Coil 2
Xw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=5.*ones(N+1,1); % Y-coordinates of the wire
Zw11=-5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(I2*u0./(4*pi*(R.^3))).*Xcross;
            By1=(I2*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(I2*u0./(4*pi*(R.^3))).*Zcross;
    
            BX3(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY3(a,b,c)=0;
            BZ3(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX3(a,b,c)=BX3(a,b,c)+Bx1(i);
                BY3(a,b,c)=BY3(a,b,c)+By1(i);
                BZ3(a,b,c)=BZ3(a,b,c)+Bz1(i);
            end
        end
    end
end

%Wire at Y=+5, Z=+5, parallel to x-axis                       : Coil 2
Xw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=5.*ones(N+1,1); % Y-coordinates of the wire
Zw11=5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(-I2*u0./(4*pi*(R.^3))).*Xcross;
            By1=(-I2*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(-I2*u0./(4*pi*(R.^3))).*Zcross;
    
            BX4(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY4(a,b,c)=0;
            BZ4(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX4(a,b,c)=BX4(a,b,c)+Bx1(i);
                BY4(a,b,c)=BY4(a,b,c)+By1(i);
                BZ4(a,b,c)=BZ4(a,b,c)+Bz1(i);
            end
        end
    end
end


%Wire at Y=+5, X=+5, parallel to z-axis                       : Coil 2
Zw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=5.*ones(N+1,1); % Y-coordinates of the wire
Xw11=5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(I2*u0./(4*pi*(R.^3))).*Xcross;
            By1=(I2*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(I2*u0./(4*pi*(R.^3))).*Zcross;
    
            BX5(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY5(a,b,c)=0;
            BZ5(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX5(a,b,c)=BX5(a,b,c)+Bx1(i);
                BY5(a,b,c)=BY5(a,b,c)+By1(i);
                BZ5(a,b,c)=BZ5(a,b,c)+Bz1(i);
            end
        end
    end
end

%Wire at Y=+5, X=-5, parallel to z-axis                       : Coil 2
Zw11=(floor(-N/2):floor(N/2)); % X-coordinates of the wire
Yw11=5.*ones(N+1,1); % Y-coordinates of the wire
Xw11=-5.*ones(N+1,1); % Z-coordinates of the wire

xp(1:Nx)=-(Nx-1)/2:(Nx-1)/2;  
yp(1:Ny)=-(Ny-1)/2:(Ny-1)/2;    
zp(1:Nz)=-(Nz-1)/2:(Nz-1)/2;  

X(1:Nx,1:Ny,1:Nz)=0;
Y(1:Nx,1:Ny,1:Nz)=0; 
Z(1:Nx,1:Ny,1:Nz)=0;

for i=1:Nx
    X(i,:,:)=xp(i); 
end
for i=1:Ny
    Y(:,i,:)=yp(i); 
end
for i=1:Nz
    Z(:,:,i)=zp(i);
end

for a=1:Nx  
    for b=1:Ny  
        for c=1:Nz
    
            for i=1:N-1
            Rx(i)=X(a,b,c)-(0.5*(Xw11(i)+Xw11(i+1)));
            Ry(i)=(Y(a,b,c)-(0.5*(Yw11(i)+Yw11(i+1))));
            Rz(i)=(Z(a,b,c)-(0.5*(Zw11(i)+Zw11(i+1))));
            dlx(i)=Xw11(i+1)-Xw11(i);
            dly(i)=Yw11(i+1)-Yw11(i);
            dlz(i)=Zw11(i+1)-Zw11(i);
            end
            
            Rx(N)=(X(a,b,c)-0.5*(Xw11(N)+1));
            Ry(N)=(Y(a,b,c)-(0.5*(Yw11(N)+1)));
            Rz(N)=(Z(a,b,c)-(0.5*(Zw11(N)+1)));
            dlx(N)=-Xw11(N)+1;
            dly(N)=-Yw11(N)+1;
            dlz(N)=-Zw11(N)+1;

            for i=1:N
                Xcross(i)=(dly(i).*Rz(i))-(dlz(i).*Ry(i));
                Ycross(i)=(dlz(i).*Rx(i))-(dlx(i).*Rz(i));
                Zcross(i)=(dlx(i).*Ry(i))-(dly(i).*Rx(i));
                R(i)=sqrt(Rx(i).^2+Ry(i).^2+Rz(i).^2);
            end

            Bx1=(-I2*u0./(4*pi*(R.^3))).*Xcross;
            By1=(-I2*u0./(4*pi*(R.^3))).*Ycross;
            Bz1=(-I2*u0./(4*pi*(R.^3))).*Zcross;
    
            BX6(a,b,c)=0;       % Initialize sum magnetic field to be zero first
            BY6(a,b,c)=0;
            BZ6(a,b,c)=0;

            for i=1:N   % loop over all current elements along coil    
                BX6(a,b,c)=BX6(a,b,c)+Bx1(i);
                BY6(a,b,c)=BY6(a,b,c)+By1(i);
                BZ6(a,b,c)=BZ6(a,b,c)+Bz1(i);
            end
        end
    end
end



%--------------visualizing the result-------------------------------------

BX=BX1+BX2+BX3+BX4+BX5+BX6+BX7+BX8;
BY=BY1+BY2+BY3+BY4+BY5+BY6+BY7+BY8;
BZ=BZ1+BZ2+BZ3+BZ4+BZ5+BZ6+BZ7+BZ8;

figure(1)

quiver3(X,Y,Z,BX,BY,BZ,2);
hold on
%%Drawing coils in red :
line([-5 5],[-5 -5], [-5 -5],'linewidth',3,'color','r');
line([-5 5],[-5 -5], [5 5],'linewidth',3,'color','r');
line([-5 5],[5 5], [-5 -5],'linewidth',3,'color','r');
line([-5 5],[5 5], [5 5],'linewidth',3,'color','r');

line([5 5],[5 5], [-5 5],'linewidth',3,'color','r');
line([-5 -5],[5 5], [-5 5],'linewidth',3,'color','r');
line([5 5],[-5 -5], [-5 5],'linewidth',3,'color','r');
line([-5 -5],[-5 -5], [-5 5],'linewidth',3,'color','r');


axis([-10 10 -10 10 -10 10])
xlabel('X-axis','fontsize',14)
ylabel('Y-axis','fontsize',14)
zlabel('Z-axis','fontsize',14)
%title('B-field of a current wire along X-axis','fontsize',14)
h=gca; 
set(h,'FontSize',14)
fh = figure(1); 
set(fh, 'color', 'white'); 

% figure(2)
% %Zoom in on central region to see uniformity :
% quiver(Y((Nx-1)/2,:,:),Z((Nx-1)/2,:,:),BY((Nx-1)/2,:,:),BZ((Nx-1)/2,:,:),2);
% hold on
% G1=plot(0,0,'.','markersize',6);
% set(G1,'MarkerEdgeColor','r')
% axis([ -5 5 -5 5])
% xlabel('Y-axis','fontsize',14)
% ylabel('Z-axis','fontsize',14)
% title('B-field YZ plane','fontsize',14)
% h=gca; 
% set(h,'FontSize',14)
% h = get(gca, 'ylabel');
% fh = figure(2); 
% set(fh, 'color', 'white'); 